# Path
JAVA_HOME=/usr/local/openjdk-8
PROJECT_PROGRAM=/usr/local

# Set Hadoop
HADOOP_HOME=$PROJECT_PROGRAM/hadoop
YARN_HOME=$HADOOP_HOME
HADOOP_YARN_HOME=$HADOOP_HOME
HADOOP_HDFS_HOME=$HADOOP_HOME
HADOOP_MAPRED_HOME=$HADOOP_HOME
HADOOP_COMMON_HOME=$HADOOP_HOME
HADOOP_INSTALL=$HADOOP_HOME
HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
HADOOP_CONFIG_HOME=$HADOOP_HOME/etc/hadoop
PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

# Set Hadoop (others)
HADOOP_OPTS="$HADOOP_OPTS -Djava.library.pathdd=$HADOOP_HOME/lib/native"
HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
HADOOP_CLASSPATH=$JAVA_HOME/lib/tools.jar

# Set HBase
HBASE_HOME=$PROJECT_PROGRAM/hbase
PATH=$PATH:$HBASE_HOME/bin

# Set Spark
SPARK_HOME=$PROJECT_PROGRAM/spark
PATH=$PATH:$SPARK_HOME/bin

# Set Zookeeper
ZOOKEEPER_HOME=$PROJECT_PROGRAM/zookeeper
PATH=$PATH:$ZOOKEEPER_HOME/bin

# Set Kafka
KAFKA_HOME=$PROJECT_PROGRAM/kafka
PATH=$PATH:$KAFKA_HOME/bin

# User
HDFS_NAMENODE_USER=hadoop
HDFS_DATANODE_USER=hadoop
HDFS_JOURNALNODE_USER=hadoop
HDFS_ZKFC_USER=hadoop
YARN_RESOURCEMANAGER_USER=hadoop
YARN_NODEMANAGER_USER=hadoop
